### ISSUE TITLE
add validations to design process

### ISSUE THREAD

**Issue by mfrederickson** [KPB-US/badgeulator#8]

**Comment by slmclane** [comment]
Added some conditionals to these artifact files in this commit: https://github.com/KPB-US/badgeulator/commit/6a8d704d69e7a2e5f274f9c7aa3c129fb899c246

FillGradient
FillRectangle
StrokeRectangle

Previously, if a required property was not present and a design was rendered, users would get a 500 error. Now, a text element indicating the erroneous artifact will be rendered on the card.
